### ISSUE TITLE
模块无法安装

### ISSUE THREAD

**Issue by Sunlice** [notadd/notadd#185]
环境：mac 10.12.6 
         Docker Version 17.06.2-ce-mac27 (19124) 
         laradock  
 安装后，能够打开后台管理界面。执行如下操作
1、克隆仓库的develop分支：
cd notadd/modules
git clone https://github.com/notadd/content.git
2、模块初始化：
cd content
composer install --no-dev
3、到 后台/全局/应用管理/模块配置/本地安装 进行模块的安装。
在第三步的时候，本地安装中列表为空，找不到已经初始化的模块，尝试几个模块均有这个问题。

**Comment by ganlanshu0211** [comment]
清除redis缓存即可

**Comment by zuohuadong** [comment]
后续版本将纠正这个问题～自动清除。 
我讲暂时关闭 此 issues ，如果有问题，清回复此issues
