### ISSUE TITLE
安装完成登录后台时报错

### ISSUE THREAD

**Issue by tianyirenjian** [notadd/notadd#194]
我下载的最新的0.11.67 版本，安装完成后登录后台报错，如下图:
![qq 20171018220659](https://user-images.githubusercontent.com/3616700/31723295-06da7286-b451-11e7-965c-6c57bf706a79.png)

**Comment by zuohuadong** [comment]
PHP7.0 请直接下载完整包

**Comment by twilroad** [comment]
什么时候下载的安装包？php7不支持自动生成秘钥对，请下载完整版的包

**Comment by zuohuadong** [comment]
https://docs.notadd.com/gettingstarted/#完整安装包

**Comment by tianyirenjian** [comment]
我使用的是 php 7.1 版本
PHP 7.1.9 (cli) (built: Aug 30 2017 18:33:57) ( NTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies。
明天测试下完整安装包，谢谢。
