### ISSUE TITLE
插件无法安装

### ISSUE THREAD

**Issue by tianyirenjian** [notadd/notadd#212]
按照官网方法安装框架，登录后台正常，无法安装插件，下载插件后，按照文档都操作完成后，在后台列表里面没有显示。把插件放到 addons 或者 extensions 文件夹下面，都无法安装， 清除 redis 缓存，也是一样。

notadd 是刚刚克隆的最新的， php 是 7.1.7 版本。

**Comment by zuohuadong** [comment]
请问是哪个插件？  部分插件还没来得及做新版的适配

**Comment by tianyirenjian** [comment]
之前测试的是 _网站 sitemap 插件_ 。我现在在测试，你们那边有哪个插件是已经可以正常安装了吗，发我个吧，我测试下。

**Comment by zuohuadong** [comment]
由于 新的SEO规则调整了，sitemap 可能安装不了

**Comment by tianyirenjian** [comment]
我现在在测试框架，还没有正式使用，有现在可以正常测试的插件吗，麻烦提供个，我测试下。

**Comment by zuohuadong** [comment]
官方开发的插件还是旧版，迁移需要时间～
