### ISSUE TITLE
win环境下使用php7.1安装会报错

### ISSUE THREAD

**Issue by zuohuadong** [notadd/notadd#216]
win环境下使用php7.1安装会报错

![image](https://user-images.githubusercontent.com/11203929/32314252-dfe893c8-bfe1-11e7-8182-c9fdcf3d9fc6.png)

**Comment by Lofanmi** [comment]
@zuohuadong 加入环境变量, 问题解决.

**Comment by tiandaye** [comment]
我试了下并没什么用

**Comment by chenjiabin** [comment]
vendor/notadd/framework/src/JWTAuth/Commands/JWTGenerateCommand.php

40行
$config = [
            'config'           => '/usr/local/openssl/openssl.cnf',
        ];
加上您的 openssl.cnf 路径，能暂时解决此问题
