### ISSUE TITLE
应用管理中的域名配置切换回Notadd后，首页会报错

### ISSUE THREAD

**Issue by dogscar** [notadd/notadd#217]
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Return value of Notadd\Foundation\Module\ModuleManager::get() must be an instance of Notadd\Foundation\Module\Module, null returned

数据库 settings表中 module.default 被设置为了 notadd/notadd
删除后即正常了

**Comment by twilroad** [comment]
暂时移除了多域名配置，故该问题已不是bug
