### ISSUE TITLE
开发者名单列表展示优化

### ISSUE THREAD

**Issue by twilroad** [notadd/notadd#223]

**Comment by zuohuadong** [comment]
LitoMore:
https://github.com/LitoMore
https://ww4.sinaimg.cn/large/0060lm7Tly1fl9comintwj308w08wwfj.jpg

寻风：
https://github.com/twilroad

依剑听雨：
https://www.zuohuadong.cn/

Seven Du
https://github.com/medz
https://ww2.sinaimg.cn/large/0060lm7Tly1fl9cu74rtpj303q03qmxv.jpg

**Comment by zuohuadong** [comment]
感谢：

半缕阳光：
https://github.com/ganlanshu0211

加菲猫：
https://github.com/mustangzhong


捐赠名单
https://blog.notadd.com/categories/月报/

**Comment by zuohuadong** [comment]
@twilroad 已更新，合并到RC
