### ISSUE TITLE
Call to undefined method Linfo\OS\Darwin::getDistro() 

### ISSUE THREAD

**Issue by yuansir** [notadd/notadd#228]
后台首页报错 `Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Linfo\OS\Darwin::getDistro() in /Users/Ryan/WebRoot/notadd/modules/administration/src/SystemInformation.php:42
Stack trace:`
看起来好像是Mac OS 下`linfo/linfo`包的问题？检查到是Darwin，但是对应的Darwin.php  缺少getDistro方法

**Comment by twilroad** [comment]
本地安装克隆的develop分支么？代码修复了，没有mac环境，劳烦帮忙测试下
