### ISSUE TITLE
根据文档未能安装扩展

### ISSUE THREAD

**Issue by wang199596** [notadd/notadd#229]
您好，我这边遇到一个好几天不能解决的问题
执行完 ：cd notadd/modules
git clone https://gitee.com/notadd/mall.git
cd mall
composer install --no-dev

composer的返回是：
Loading composer repositories with package information
Updating dependencies
Writing lock file
Generating autoload files

后台/全局/应用管理 并没有任何改变 

或者根文档流程进行，  后台/全局/应用管理/插件配置/本地安装 这个目录也是没有反应

**Comment by zuohuadong** [comment]
商城目前在开发中，未能对新版进行适配

**Comment by wang199596** [comment]
好的谢谢
