### ISSUE TITLE
如何在模块中定义 计划任务

### ISSUE THREAD

**Issue by imvkmark** [notadd/notadd#235]
因为默认的 kernel 是定义在框架中.
所以如果在框架中定义是可取的
但是在模块中如何定义计划任务, 这个还是有些疑问的

**Comment by zuohuadong** [comment]
@twilroad @medz

**Comment by twilroad** [comment]
可以基于事件机制来实现队列执行的逻辑

**Comment by imvkmark** [comment]
@twilroad 计划任务是 schedule , 定时执行, 事件机制完成不了这种功能.

**Comment by imvkmark** [comment]
这个可以使用以下方式, 参考 OctoberCMS
```
$this->app['events']->fire('console.schedule', [$schedule]);
```
