### ISSUE TITLE
增加本地没安装redis 时的提示

### ISSUE THREAD

**Issue by zuohuadong** [notadd/notadd#236]
redis 未安装或未运行

**Comment by twilroad** [comment]
Debug 模式下：
![image](https://user-images.githubusercontent.com/5193767/33807424-d843c644-de11-11e7-9205-c75eb7fd5ff4.png)
非 Debug 模式下：
![image](https://user-images.githubusercontent.com/5193767/33807581-e7a4b150-de13-11e7-8554-1b6ade990606.png)
