### ISSUE TITLE
全局设置的参数设置不管用

### ISSUE THREAD

**Issue by ganlanshu0211** [notadd/notadd#239]
![image](https://user-images.githubusercontent.com/9670379/33696300-95c7b168-db3c-11e7-8e8c-c86e81263e52.png)

![image](https://user-images.githubusercontent.com/9670379/33696198-0bf8e1fa-db3c-11e7-8dd7-681341d4d8ed.png)
编辑参数，确认提交
![image](https://user-images.githubusercontent.com/9670379/33696205-13937466-db3c-11e7-8ea0-2a10d56e6481.png)
提示提交成功，但是页面变空白
![image](https://user-images.githubusercontent.com/9670379/33696240-42bb2f4a-db3c-11e7-8028-9b471dc5d52c.png)
再进去，设置没变

**Comment by zuohuadong** [comment]
我这边内容有改变，不过不自动跳转

**Comment by ganlanshu0211** [comment]
跳转正常了，但是内容还是没改变。删除缓存后内容改变

**Comment by ganlanshu0211** [comment]
站点关闭失败

**Comment by zuohuadong** [comment]
@twilroad
