### ISSUE TITLE
系统设置，菜单管理，关掉某个菜单后，菜单依然存在，已保存，已刷新

### ISSUE THREAD

**Issue by ganlanshu0211** [notadd/notadd#241]
![image](https://user-images.githubusercontent.com/9670379/33696680-5b2db064-db3e-11e7-98fc-33eca630fec7.png)
![image](https://user-images.githubusercontent.com/9670379/33696665-48314afc-db3e-11e7-8996-749143deed1d.png)

**Comment by twilroad** [comment]
fixed：
![image](https://user-images.githubusercontent.com/5193767/33807274-17320fd0-de0f-11e7-9aa0-5db177e5b722.png)
