### ISSUE TITLE
SEO模板排序不能用

### ISSUE THREAD

**Issue by ganlanshu0211** [notadd/notadd#242]
![image](https://user-images.githubusercontent.com/9670379/33696680-5b2db064-db3e-11e7-98fc-33eca630fec7.png)
![image](https://user-images.githubusercontent.com/9670379/33697119-4fe67cac-db40-11e7-86d2-fe0874f10170.png)
回车后，依然是0，顺序不变

**Comment by twilroad** [comment]
本地测试有效：
![image](https://user-images.githubusercontent.com/5193767/33807171-7501b270-de0d-11e7-9c17-12b261f555bc.png)
![image](https://user-images.githubusercontent.com/5193767/33807173-81088d1e-de0d-11e7-9086-d143220d8cfa.png)
