### ISSUE TITLE
添加模板后，编辑模板，没有东西可编辑

### ISSUE THREAD

**Issue by ganlanshu0211** [notadd/notadd#243]
![image](https://user-images.githubusercontent.com/9670379/33697181-a010f82e-db40-11e7-9bf8-cf6bc9ef7cc5.png)
![image](https://user-images.githubusercontent.com/9670379/33697167-8e7e8d7e-db40-11e7-8148-718ff0d33be1.png)

**Comment by twilroad** [comment]
需要安装插件 https://github.com/notadd/ext-monaco
