### ISSUE TITLE
批量删除模板失败

### ISSUE THREAD

**Issue by ganlanshu0211** [notadd/notadd#244]
![image](https://user-images.githubusercontent.com/9670379/33697181-a010f82e-db40-11e7-9bf8-cf6bc9ef7cc5.png)
![image](https://user-images.githubusercontent.com/9670379/33697198-b7b0cc48-db40-11e7-9d7b-5552c5b0cb22.png)

**Comment by twilroad** [comment]
能否提供详细的错误提示，本地测试，无此问题

**Comment by ganlanshu0211** [comment]
![image](https://user-images.githubusercontent.com/9670379/33814475-568a2f9a-de65-11e7-9644-162bf332626f.png)

点击删除后，显示如下
![image](https://user-images.githubusercontent.com/9670379/33814457-46dcd4ee-de65-11e7-8b05-90898e636708.png)
点击批量更新没反应
刷新后内容还在
![image](https://user-images.githubusercontent.com/9670379/33814508-8eff37ee-de65-11e7-834f-0b0687d467bf.png)
