### ISSUE TITLE
数据库正常，而 redis 地址错误时的优化

### ISSUE THREAD

**Issue by zuohuadong** [notadd/notadd#249]
![image](https://user-images.githubusercontent.com/11203929/33819305-b1cdde3c-de84-11e7-86ca-bc8bcb865e90.png)

**Comment by zuohuadong** [comment]
应该提示 redis 无法连接（地址错误，未安装或未启动）

**Comment by limhu** [comment]
![image](https://user-images.githubusercontent.com/17063861/34703453-fa6e7d9e-f52d-11e7-801e-21f0e4677d8f.png)
对此redis异常增加处理方式
