### ISSUE TITLE
后台点击全局不显示开发者信息和关于信息

### ISSUE THREAD

**Issue by zuohuadong** [notadd/notadd#253]
后台点击全局不显示开发者信息和关于信息

**Comment by 1459416736** [comment]
请问运行环境是什么？

**Comment by zuohuadong** [comment]
![image](https://user-images.githubusercontent.com/11203929/34597517-0e8baaf4-f222-11e7-8cb7-833a6880d402.png)
官方demo ～ 装的是 RC1 应该少了东西
