### ISSUE TITLE
某些栏目报错的问题

### ISSUE THREAD

**Issue by onep2p** [notadd/notadd#255]
1、确定扩展没我呢提
2、确定redis没有问题
3、能够登录后台

问题是，应用管理中所有子栏目和调试工具无法打开   修改提交的也不行    都报同一个错误

附图：（好像无法传图片~）

**Comment by zuohuadong** [comment]
测试没发现这个问题～ 请上传截图   （图片直接拖进来就行了。QQ截图也可以直接粘贴）
