### ISSUE TITLE
后台 server error 问题

### ISSUE THREAD

**Issue by zuohuadong** [notadd/notadd#256]
刷新也是server error
 必须重新登录才正常
  应该是长时间不登录导致，但是没自动跳转到登录页，也没有说登录信息过期的提示

**Comment by zuohuadong** [comment]
![image](https://user-images.githubusercontent.com/11203929/34599127-c546e426-f22b-11e7-9373-40eee637f3d7.png)

**Comment by ellermister** [comment]
你好，`Server Error`  一般在系统产生错误后抛出的默认提示。
可开启 DEBUG 模式，查看详细错误调用。

`/vendor/notadd/framework/configurations/app.php`
修改 debug 为 true

浏览器端可以打开调试控制台(F12)进行查看具体详细错误。

如有问题请复制相关内容并截图反馈。
