### ISSUE TITLE
安装完后  后台打开 这样的

### ISSUE THREAD

**Issue by ming200825** [notadd/notadd#258]
![qq 20180105191111](https://user-images.githubusercontent.com/4900401/34606963-61f2462e-f24c-11e7-8996-30778fd3a2e9.png)

**Comment by zuohuadong** [comment]
server error 问题目前在排查，你改下 路由  /admin/#

**Comment by zuohuadong** [comment]
https://docs.notadd.com/#/v1/zh-cn/gettingstarted  安装对应拓展～
