### ISSUE TITLE
长时间没访问后登录后台空白

### ISSUE THREAD

**Issue by zuohuadong** [notadd/notadd#260]
提示请重新登录，但是页面并没跳转，刷新后正常
系统：Linux
PHP: 7.1
![image](https://user-images.githubusercontent.com/11203929/34816863-2c62269c-f6f1-11e7-9e8e-b8ca92165b74.png)

**Comment by zuohuadong** [comment]
@1459416736  https://demo.notad.com/admin

**Comment by 1459416736** [comment]
@zuohuadong 这个问题我解决了下，测试对了，我提交上去

**Comment by zuohuadong** [comment]
@1459416736  666
