### ISSUE TITLE
数据库为啥必须要密码？

### ISSUE THREAD

**Issue by niefufeng** [notadd/notadd#261]
我数据库就是没有密码，留空居然还不能点击下一步！

**Comment by jayleco** [comment]
数据库没密码相当于你家房门没有锁，你敢敞着门在家洗澡、拉屎、看黄片吗？😄一个道理啦

**Comment by zuohuadong** [comment]
出于安全考虑，不论是开发环境还是线上环境，都建议设置密码。。。

**Comment by niefufeng** [comment]
@jayleco 道理我都懂，可是我就是开着门的啊。。。（在农村晚上开着门没有影响啊233）

**Comment by niefufeng** [comment]
@zuohuadong 这个我知道，只是个人觉得这个不应该在程序层面限制

**Comment by jayleco** [comment]
@niefufeng 霸气，农村民风淳朴，网上大家都有窥私欲，还是安全点把门关上装个密码锁比较靠谱点

**Comment by zuohuadong** [comment]
@niefufeng 可以参见 Redis 空密码事件，如果养成这个习惯，这个问题会逐渐演变为程序不安全。
