### ISSUE TITLE
2.0 Beta2 后台长时间未登录，没提示重新登录～

### ISSUE THREAD

**Issue by zuohuadong** [notadd/notadd#296]
2.0 Beta2 后台长时间未登录，没提示重新登录～

应该设定一定时间后过期重新登录

**Comment by zilveer** [comment]
Can you please write in English, thanks.

**Comment by zuohuadong** [comment]
@zilveer 2.0 Beta2 the background for a long time not logged in, no prompts to log in again. You should log back in after a certain amount of time.
