### ISSUE TITLE
安装好之后运行报错

### ISSUE THREAD

**Issue by rumbleKK** [notadd/notadd#299]
错误信息如下：
/Users/lihuikang/my/notadd/node_modules/@notadd/injection/dashboards/developer.dashboard.js:31
    common_1.Injectable()
             ^

TypeError: common_1.Injectable is not a function
    at Object.<anonymous> (/Users/lihuikang/my/notadd/node_modules/@notadd/injection/dashboards/developer.dashboard.js:31:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/lihuikang/my/notadd/node_modules/@notadd/injection/dashboards/index.js:3:29)
    at Module._compile (module.js:624:30)

**Comment by rumbleKK** [comment]
执行环境：
MAC系统 node 8.5

**Comment by twilroad** [comment]
```@notadd/injection```这个包的版本多少？

**Comment by rumbleKK** [comment]
2.4.2

**Comment by baisheng** [comment]
报同样错误 Mac Node v8.11.2

**Comment by twilroad** [comment]
看下```@nestjs/common```的版本号是多少

**Comment by baisheng** [comment]
@twilroad  "version": "4.6.6"

**Comment by baisheng** [comment]
升级到 5.0.1 后，不报这个错误，会报 Error: Cannot find module '@nestjs/typeorm/typeorm.utils'

**Comment by twilroad** [comment]
@baisheng ```@nestjs/typeorm``` 和 ```typeorm``` 这两个包的版本分别是多少？

**Comment by baisheng** [comment]
@twilroad <code>@netjs/typeorm</code>   "version": "5.0.0" <code>typeorm</code>  "version": "0.2.6"

**Comment by rumbleKK** [comment]
@twilroad 升级@nestjs/common @nestjs/typeorm 到5.0版本也是报错

**Comment by twilroad** [comment]
```
yarn run v1.6.0
$ node ./node_modules/gulp/bin/gulp.js
[17:55:33] Using gulpfile /home/code/notadd-async/gulpfile.js
[17:55:33] Starting 'default'...
[17:55:33] Finished 'default' after 62 ms
[17:55:33] [nodemon] 1.17.5
[17:55:33] [nodemon] to restart at any time, enter `rs`
[17:55:33] [nodemon] watching: ormconfig.yml packages/**/* storages/addons/enabled.yaml storages/modules/enabled.yaml
[17:55:33] [nodemon] starting `node node_modules/@notadd/server/bootstrap.js`

                 _            _     _
     _ __   ___ | |_ __ _  __| | __| |
    | "_ \ / _ \| __/ _` |/ _` |/ _` |
    | | | | (_) | || (_| | (_| | (_| |
    |_| |_|\___/ \__\__,_|\__,_|\__,_|

        
[Notadd] 101789   - 2018-5-30 17:55:46   [NestFactory] Starting Nest application... +9097ms
[Notadd] 101789   - 2018-5-30 17:55:46   [InstanceLoader] ApplicationModule dependencies initialized +60ms
[Notadd] 101789   - 2018-5-30 17:55:46   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Notadd] 101789   - 2018-5-30 17:55:46   [InstanceLoader] WebsocketModule dependencies initialized +1ms
[Notadd] 101789   - 2018-5-30 17:55:46   [InstanceLoader] BackendModule dependencies initialized +0ms
[Notadd] 101789   - 2018-5-30 17:55:46   [InstanceLoader] InjectionModule dependencies initialized +1ms
[Notadd] 101789   - 2018-5-30 17:55:46   [InstanceLoader] GraphQLModule dependencies initialized +0ms
[Notadd] 101789   - 2018-5-30 17:55:46   [InstanceLoader] InternationalizationModule dependencies initialized +1ms
[Notadd] 101789   - 2018-5-30 17:55:46   [InstanceLoader] GraphqlModule dependencies initialized +1ms
[Notadd] 101789   - 2018-5-30 17:55:49   [InstanceLoader] TypeOrmCoreModule dependencies initialized +2811ms
[Notadd] 101789   - 2018-5-30 17:55:49   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Notadd] 101789   - 2018-5-30 17:55:49   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Notadd] 101789   - 2018-5-30 17:55:49   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Notadd] 101789   - 2018-5-30 17:55:49   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Notadd] 101789   - 2018-5-30 17:55:58   [InstanceLoader] LoggerModule dependencies initialized +8733ms
[Notadd] 101789   - 2018-5-30 17:55:58   [InstanceLoader] SettingModule dependencies initialized +1ms
[Notadd] 101789   - 2018-5-30 17:55:58   [InstanceLoader] WorkflowModule dependencies initialized +0ms
[Notadd] 101789   - 2018-5-30 17:55:58   [InstanceLoader] DashboardModule dependencies initialized +0ms
[Notadd] 101789   - 2018-5-30 17:55:58   [InstanceLoader] PageModule dependencies initialized +1ms
[Notadd] 101789   - 2018-5-30 17:55:58   [InstanceLoader] ExtensionModule dependencies initialized +1ms
[Notadd] 101789   - 2018-5-30 17:55:58   [InstanceLoader] ModuleModule dependencies initialized +0ms
[Notadd] 101789   - 2018-5-30 17:55:58   [InstanceLoader] AddonModule dependencies initialized +1ms
[Notadd] 101789   - 2018-5-30 17:55:58   [InstanceLoader] LocalModule dependencies initialized +0ms
[Notadd] 101789   - 2018-5-30 17:55:58   [InstanceLoader] UserModule dependencies initialized +1ms
[Notadd] 101789   - 2018-5-30 17:55:58   [RoutesResolver] LoginController {/user}: +135ms
[Notadd] 101789   - 2018-5-30 17:55:58   [RouterExplorer] Mapped {/login, POST} route +4ms
[Notadd] 101789   - 2018-5-30 17:55:58   [RoutesResolver] WechatLoginController {/user/wechat}: +2ms
[Notadd] 101789   - 2018-5-30 17:55:58   [RouterExplorer] Mapped {/login, POST} route +3ms
[Notadd] 101789   - 2018-5-30 17:55:58   [RoutesResolver] FileController {/local/file}: +1ms
[Notadd] 101789   - 2018-5-30 17:55:58   [RouterExplorer] Mapped {/download, GET} route +1ms
[Notadd] 101789   - 2018-5-30 17:55:58   [RouterExplorer] Mapped {/upload, POST} route +1ms
[Notadd] 101789   - 2018-5-30 17:55:58   [RouterExplorer] Mapped {/visit/:bucketName/:fileName, GET} route +1ms
[Notadd] 101789   - 2018-5-30 17:55:58   [NestApplication] Nest application successfully started +151ms
[Notadd] 101789   - 2018-5-30 17:55:58   [NotaddFactory] Graphql IDE Server on: http://192.168.120.120:3000/graphiql +13ms
[Notadd] 101789   - 2018-5-30 17:55:58   [NotaddFactory] Server on: http://192.168.120.120:3000 +0ms
```
我这边全线安装后，正常运行。

**Comment by rumbleKK** [comment]
更新新的package.json之后报错：
module.js:529
    throw err;
    ^

Error: Cannot find module '@nestjs/typeorm/typeorm.utils'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/lihuikang/my/notadd/test.js:1:63)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

把'@nestjs/typeorm/typeorm.utils'修改为'@nestjs/typeorm/dist/typeorm.utils'可以成功运行了

yarn run v1.7.0
$ node ./node_modules/gulp/bin/gulp.js
[19:18:52] Using gulpfile ~/my/notadd/gulpfile.js
[19:18:52] Starting 'default'...
[19:18:52] Finished 'default' after 178 ms
[19:18:52] [nodemon] 1.17.5
[19:18:52] [nodemon] to restart at any time, enter `rs`
[19:18:52] [nodemon] watching: ormconfig.yml packages/**/* storages/addons/enabled.yaml storages/modules/enabled.yaml
[19:18:52] [nodemon] starting `node node_modules/@notadd/server/bootstrap.js`

WARNING!!
The @Component() decorator is deprecated and will be removed within next major release. Use @Injectable() instead.



                 _            _     _
     _ __   ___ | |_ __ _  __| | __| |
    | "_ \ / _ \| __/ _` |/ _` |/ _` |
    | | | | (_) | || (_| | (_| | (_| |
    |_| |_|\___/ \__\__,_|\__,_|\__,_|


[Notadd] 9087   - 2018-5-30 19:19:05   [NestFactory] Starting Nest application... +8034ms
[Notadd] 9087   - 2018-5-30 19:19:05   [InstanceLoader] ApplicationModule dependencies initialized +144ms
[Notadd] 9087   - 2018-5-30 19:19:05   [InstanceLoader] TypeOrmModule dependencies initialized +0ms

**Comment by twilroad** [comment]
推荐使用npm官方镜像源进行安装
