### ISSUE TITLE
为什么 windows 10 不能安装？

### ISSUE THREAD

**Issue by haibo5** [notadd/notadd#313]
yarn run v1.12.3
error Command "run:install" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

windows 10

安装

执行 NPM 包安装

yarn install

安装数据库配置：

yarn run:install

必须使用 yarn ！！！必须使用 yarn ！！！必须使用 yarn ！！！

按照这个 https://docs.notadd.com/#/v2/zh-cn/gettingstarted?id=%e5%ae%89%e8%a3%85

**Comment by zuohuadong** [comment]
请按 readme 进行安装，目前版本 4.x 。
docs 目前是旧的2.x文档
