### ISSUE TITLE
nest 

### ISSUE THREAD

**Issue by yangchongduo** [notadd/notadd#314]
node 这边使用nest 感觉不太多

**Comment by zuohuadong** [comment]
> node 这边使用nest 感觉不太多

nest 是真正意义上的后端框架，这个是必然趋势了。

express  koa  egg 这些只能称之为 工具包...

**Comment by yangchongduo** [comment]
egg 他们声称 ：egg  可是经过双十一洗礼的，  国内用node 做后端的还是比较少的，对于一个大前端 egg 已经不错了

**Comment by zuohuadong** [comment]
1. 阿里自己参考nest 做了 midway 。
2. egg 如果好用的话就不会被nest 超越得这么快了。
3. 你看懂 nest 就会明白，这才是一个后端框架应有的样子。
4. 如果你是前端，需要个工具包，可以选择express koa 。如果你真的拿来做后端，就按后端的标准来吧

**Comment by yangchongduo** [comment]
你看错了 nest 和egg 现在下载量差不多，不过 你说的很有道理

**Comment by zuohuadong** [comment]
https://npmcharts.com/compare/egg,@nestjs/core

参见这个趋势图
