### ISSUE TITLE
这个应用非常棒，持续关注

### ISSUE THREAD

**Issue by karllo** [notadd/notadd#80]
有时间的话希望加入又拍云的云储存插件em

**Comment by karllo** [comment]
![image](https://user-images.githubusercontent.com/9446682/26958981-36def9c4-4d00-11e7-8e14-2e2335ac9d3c.png)
用户中心的用户列表显示问题

**Comment by zuohuadong** [comment]
后台对 1680X1050 不再承诺支持， 小于这个分辨率的 可以通过缩放网页～

**Comment by karllo** [comment]
![image](https://user-images.githubusercontent.com/9446682/26959082-de28cebc-4d00-11e7-9b9a-3d3a4c5ac1b2.png)

默认页面比如这样
![image](https://user-images.githubusercontent.com/9446682/26959118-08422478-4d01-11e7-8e57-dae13848d24f.png)

页面打开最好有个默认页面，额一开始我还以为挂掉了

**Comment by zuohuadong** [comment]
后面会加个提示～～

**Comment by zuohuadong** [comment]
这块的默认页面其实是数据展示页面，只不过还没开发。
